from graph import build_graph
from output_writer import write_project_to_disk

def main():
    app = build_graph()

    initial_state = {
        "user_request": "I want to build an e-commerce store for selling clothes, "
        "with a shopping cart and a login page",
    }

    result = app.invoke(initial_state)

    print("=" * 50)
    print("Brief generated by CEO Agent:")
    print("=" * 50)
    print(result.get("brief"))

    print()
    print("=" * 50)
    print("Requirements generated by Analysis Agent:")
    print("=" * 50)
    print(result.get("requirements"))

    print()
    print("=" * 50)
    print("Tasks generated by PM Agent:")
    print("=" * 50)
    print(result.get("tasks"))

    print()
    print("=" * 50)
    print("Code generated by Frontend/Backend/Database/AI Agents:")
    print("=" * 50)
    print(result.get("generated_code"))

    print()
    print("=" * 50)
    print("Final QA report:")
    print("=" * 50)
    print(result.get("qa_report"))

    print()
    print("=" * 50)
    print("Integration report (cross-agent consistency check):")
    print("=" * 50)
    print(result.get("integration_report"))

    print()
    print("=" * 50)
    print(f"Final status: {result.get('status')}")
    print("=" * 50)
    if result.get("status") == "escalated":
        print(result.get("escalation_reason"))
    if result.get("retry_count"):
        print("Retry counts:", result.get("retry_count"))

    if result.get("generated_code"):
        project_name = (result.get("requirements") or {}).get("project_type", "project")
        write_result = write_project_to_disk(result["generated_code"], project_name=project_name)

        print()
        print("=" * 50)
        print("Project saved to disk:")
        print("=" * 50)
        print(write_result["project_folder"])
        for path in write_result["files_written"]:
            print(f"  - {path}")

if __name__ == "__main__":
    main()