from graph import build_graph

def main():
    app = build_graph()

    initial_state = {
        "user_request": "I want to build an e-commerce store for selling clothes, "
        "with a shopping cart and a login page",
    }

    result = app.invoke(initial_state)

    print("=" * 50)
    print("Brief generated by CEO Agent:")
    print("=" * 50)
    print(result.get("brief"))
    
if __name__ == "__main__":
    main()